version: "3"

name: productized-store

services:
  db:
    image: bitnami/mysql:latest
    container_name: productized-store-db
    restart: "no"
    environment:
      MYSQL_ROOT_USER: dev
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: productized-store
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - productized-store-data:/bitnami/mysql/data
    ports:
      - 3306:3306
volumes:
  productized-store-data:
    driver: local
