import type { Metadata } from 'next';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

export const metadata: Metadata = {
  title: "Productized Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={GeistMono.className}>
        <Theme
          appearance="light"
          accentColor="blue"
          scaling="110%"
          radius="medium"
          panelBackground="translucent"
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
